### ISSUE TITLE
`bintray_upload.gradle` fails when lacking `local.properties`

### ISSUE THREAD

**Issue by roastduck** [isanwenyu/BintrayUploadGradle#1]
`bintray_upload.gradle` is failing when there is no `local.properties`, which might happen in remote builds (e.g. Travis-CI tests).

My suggestion is to check whether `local.properties` exists in [bintray_upload.gradle:79](https://github.com/isanwenyu/BintrayUploadGradle/blob/master/bintray_upload.gradle#L79).

**Comment by isanwenyu** [comment]
I think the better option is that you can add the command `touch local.properties && echo 'user=\napiKey=' >> local.properties` in the` before_install` section of the travis configuration file.
You can also add `deploy: provider: bintray` in travis coinfig file to deploy your build artifacts to Bintray.

**Comment by roastduck** [comment]
Thanks. Actually `touch local.properties` is enough.
